// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7HMIzlWQ6PsLh5KXvImaZK_8qQzisSr4',
    appId: '1:929631250454:web:761e8e76df57f2fae2ed37',
    messagingSenderId: '929631250454',
    projectId: 'digi-wallet-99',
    authDomain: 'digi-wallet-99.firebaseapp.com',
    storageBucket: 'digi-wallet-99.firebasestorage.app',
    measurementId: 'G-J596MZY0HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkBDK_a_ICtrjLNLLDiEHHqOrcnuW59CA',
    appId: '1:929631250454:android:9257ea79d119bc69e2ed37',
    messagingSenderId: '929631250454',
    projectId: 'digi-wallet-99',
    storageBucket: 'digi-wallet-99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_eWcwABF35yjfxlVHV-ZagIW2mHF3z7w',
    appId: '1:929631250454:ios:21c78b69b29d962ae2ed37',
    messagingSenderId: '929631250454',
    projectId: 'digi-wallet-99',
    storageBucket: 'digi-wallet-99.firebasestorage.app',
    iosBundleId: 'com.example.digiWallett',
  );
}
